### ISSUE TITLE
What CAD/CAM was used?

### ISSUE THREAD

**Issue by MrAureliusR** [lophtware/UsbCPic32Breakout#2]
The schematics for the Lite variant are just 1-Lite.sch. There are a number of CAD/CAM that use .sch for schematics; I use KiCAD and it wasn't able to recognize the file. I'm assuming it's probably Eagle or perhaps Altium but I'd like to know for sure. I'm going to fire up my Windows VM and download Eagle to give it a try. It's probably worth mentioning this somewhere in that directory, or in the README!

Cheers 👍🏼

**Comment by MrAureliusR** [comment]
After a lot of searching, it seems to be DesignSpark, which is Windows-only and proprietary. It'd be awesome if you could either add a .PDF or export the schematics in a format readable by open-source software!

**Comment by lophtware** [comment]
I think you're right, I've not mentioned DesignSpark.  Version 8.1.2 was used for this project.  I'll update the README and the wiki to reflect that.

Have you seen the [wiki](https://github.com/lophtware/UsbCPic32Breakout/wiki) ?  Bottom link is a PDF to the schematics, although that's the Full Fat version.  The schematics for both boards are also included along with the firmware in the [releases](https://github.com/lophtware/UsbCPic32Breakout/releases).

There is only a single page of schematics for the Lite board as there really isn't much to it.  Basically a voltage regulator and the PIC.

All of this was designed and put together under a GNU/Linux environment (Fedora) so you shouldn't need any Windows installation to work with the project.  I chose DesignSpark (many years ago...) because it was freely available and could be run on a GNU/Linux machine and didn't have any of the limitations of Eagle; I tried to like it but the board size limitation for the free edition was a deal breaker.  At the time, the GNU EDA project that I was using had an excellent PCB layout package but the schematic capture and integration of the various tools were poor.  Since then it's become KiCad and a lot more polished, but once you've built up a library of components and invested the time in a particular tool it becomes hard to switch.  That said, I've recently revisited KiCad and I'm actually using that for my projects going forwards.  It's still a bit klunky in places (ie. the pin rules, labels and assignment, text orientation / formatting, lack of class-based net sizing, etc. etc.) but it's come on leaps and bounds from where it was.  Plus it's 'free free'.

I hope this answers your questions, but let me know if you need anything else.

Cheers.

**Comment by MrAureliusR** [comment]
Huh, looking at the website for DesignSpark it seems to imply a Windows 10 environment is required. I'll check again. Are you using WINE?

EDIT: What I'm really trying to figure out is which PGED/PGEC pair is broken out on the Lite. The text in the schematic says PGED/PGEC1 but the pin labels say PGED/PGEC2.

**Comment by lophtware** [comment]
Yeah, check out PlayOnLinux - it handles a lot of the wine config for you and will allow you to have separate wine configurations for different applications if you need to.  Apart from the pre-requisite .NET libraries I can't remember anything special to get it running.  There are a couple of guides on t'interweb from memory.

The pins are PGEC2 (pin 27) / PGED2 (pin 28) - I've just checked the schematic in DesignSpark, the PDF from the release tarball and the PIC32MM0256GPM028 datasheet and they all agree.  The Full Fat board is also PGE2.  Which schematic says PGE1, and I'll get that amended ?

**Comment by MrAureliusR** [comment]
It was the full fat schematic, the note next to the programming pins says PGEC/PGED1
![image](https://user-images.githubusercontent.com/41264289/199941432-f1596303-1493-4add-842d-cf9c23bee6da.png)

**Comment by lophtware** [comment]
Ah, right.  Yes.  So in the Full Fat version you can program the PIC over USB if you kick it into Debug Accessory Mode (you'd need to knock up your own cable for this).  The USB D+/D- lines are multiplexed with PGE2.  However, that note is trying to say PGE1 is also exposed on the headers for programming without a USB dongle - check out RB0 and RB1.

The PGE1 interface is also broken out on the Lite board via RB0 and RB1 and they're next to the PGE2 pins on the header.  But it makes sense to use the PGE2 interface on the Lite board because the first five pins of that header are pinout-compatible with the PICKit.  That's something I wish I'd put more effort into for the green board, but routing was a bit of a pain so you need to cross over some wires.

For programming these PICs you can use any of the PGE* interfaces as long as you use the clock / data lines are from the same interface and it'll work, ie. don't use PGEC1 with PGED2.  For debugging (ICE/ICD) you need to pre-select which interface you want to use, which is done with the FICD register in the config words - these bits don't affect programming.  The default is PGE1.

Hope this helps.

**Comment by MrAureliusR** [comment]
I have a lot of experience using PIC32 devices, I've just never used the PIC32MM line before, so I'm just feeling out what is different about them. Good to know it's PGED/C2, I had 1 in my config bits and thought it was my oscillator config that was causing debugging to fail.
